apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: "2023-03-23T15:02:23Z"
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        "f:spec":
          .: {}
          "f:finally": {}
          "f:params": {}
          "f:resources": {}
          "f:tasks": {}
          "f:workspaces": {}
      manager: Mozilla
      operation: Update
      time: "2023-03-23T15:02:23Z"
  name: mobb-aro-tf
  namespace: openshift-operators
  resourceVersion: "60723321"
  uid: 8e113b7b-d5c5-4327-9366-7c17208b99fb
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: "https://github.com/rh-mobb/terraform-aro"
        - name: revision
          value: main
        - name: submodules
          value: "true"
        - name: depth
          value: "1"
        - name: sslVerify
          value: "true"
        - name: crtFileName
          value: ca-bundle.crt
        - name: deleteExisting
          value: "true"
        - name: verbose
          value: "true"
        - name: gitInitImage
          value: >-
            gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.40.2
        - name: userHome
          value: /home/git
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: mobb-tf
        - name: ssh-directory
          workspace: mobb-tf
        - name: basic-auth
          workspace: mobb-tf
        - name: ssl-ca-directory
          workspace: mobb-tf
    - name: terraform
      taskRef:
        name: terraform-cli
      workspaces:
        - name: source
          workspace: source
      params:
        - name: terraform-secret
          value: "terraform-secret"
        - name: ARGS
          value:
            - apply
            - "-auto-approve"
  workspaces:
    - name: mobb-tf
